# fly.toml file generated for da-kurs on 2023-04-07T09:52:42+02:00

app = "da-kurs"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "waw"
processes = []

[env]
  ASPNETCORE_URLS="http://+:8080"

[build]
  image = "kuba7pg/datingapp:latest"
  CloudinarySettings__CloudName="dduvmvsic"
  CloudinarySettings__ApiKey="672535928913617"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
